export { Best } from './Best/Best';
export { About } from './About/About';
export { Header } from './Header/Header';
export { Loungewear } from './Loungewear/Loungewear';
export { BrandSlider } from './BrandSlider/BrandSlider';
export { LoungewearSlider } from './LoungewearSlider/LoungewearSlider';
export { Comfort } from './Comfort/Comfort';
export { ComfortSlider } from './ComfortSlider/ComfortSlider';
// export {  } from './';
